### ISSUE TITLE
Fix PostgrSQL compatibility

### ISSUE THREAD

**Issue by didierm** [BernieO/calcardbackup#10]
Occurances of the `psql` command with **dbhost** and/or **dbprotocol** arguments require proper option assignments  :
 
```psql "${dbhost}" "${dbprotocol}" ```
becomes
```psql -h "${dbhost}" -p "${dbprotocol}" ```

**Comment by BernieO** [comment]
The option assigment is already stored within the variables ${dbhost} and ${dbprotocol}. See here:
https://github.com/BernieO/calcardbackup/blob/master/calcardbackup#L482-L486
https://github.com/BernieO/calcardbackup/blob/master/calcardbackup#L493-L497

In my instances this works without any problems and according to the documentation this is valid syntax for psql :
https://www.postgresql.org/docs/9.6/static/app-psql.html

Does calcardbackup throw an error when you use it with PostgreSQL?

**Comment by didierm** [comment]
Yes, it throws an error : 
`psql: FATAL:  Peer authentication failed for user "oc_owner00"`

`${dbcommand}` never acquires the "--host" assignment, hence I guess there's an issue with the regexp logic in https://github.com/BernieO/calcardbackup/blob/master/calcardbackup#L475-L501 .

```
$ psql -V
psql (PostgreSQL) 9.2.24

$ grep db config.php : 
  'dbtype' => 'pgsql',
  'dbname' => 'oc_cloud00',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_owner00',
  'dbpassword' => '*****,`
```

**Comment by BernieO** [comment]
Aaahrg!! Found it. Sorry!

If neither port nor socket is present in dbhost from config.php, "--host" was not assigned.

Can you check whether this commit from the testing branch solves your problem (adding lines 574 and 575 is enough): https://github.com/BernieO/calcardbackup/commit/5dcc39f3115270fe1909b5f2f5436a3214f00979

Thanks for finding this 👍

**Comment by didierm** [comment]
Works great, thanks !
