### ISSUE TITLE
Shebang and interop

### ISSUE THREAD

**Issue by daviddahlberg** [BernieO/calcardbackup#13]
Using the script on OpenBSD I noticed the following interop issue:

* The shebang is "#!/bin/bash"

Background:
On some operating sytems you do not find bash in "/bin", but in "/usr/bin" or "/usr/local/bin". This is at least true on OpenBSD and FreeBSD, I expect this on Mac OS and Solaris and probably some non-mainstream Linux Distros (esp. lightweight ones).

Possible solution:
"#!/usr/bin/env bash" is POSIX compatible and should work almost everywhere, where bash is installed into the $PATH.

**Comment by BernieO** [comment]
Thanks for the detailed description and suggestion.
Fixed in https://github.com/BernieO/calcardbackup/commit/db00b2d7f66135a42d525cbd07a53ba51c8a0bd6
