### ISSUE TITLE
readlink(1) on non-GNU systems

### ISSUE THREAD

**Issue by daviddahlberg** [BernieO/calcardbackup#14]
Using the script on OpenBSD I noticed the following interop issue:

* readlink -vf

Flag support overview:
OpenBSD, FreeBSD have: -f
NetBSD has: both
Dragonfly has: neither
Busybox has: both
GNU has: both

Proposed solution:
I think, you could get rid of "-v". For error reporting you already use $? anyway. You could enrich the error message with the used argument, if you want this information to be displayed.

Edit: Former, similar issue '-m' in #4

**Comment by BernieO** [comment]
Thanks for this one as well 👍 
fixed in https://github.com/BernieO/calcardbackup/commit/610364bdf3cec9992cedb49cefcc2af6201dd4fc
