### ISSUE TITLE
Nothing is backed up with an empty value for dbtableprefix

### ISSUE THREAD

**Issue by cburki** [BernieO/calcardbackup#16]
An empty `dbtableprefix` does not always mean that it is the default `oc_`. It can mean it is no prefix.
```
  # set default dbtableprefix if empty or not found in config.php:
  [[ -z "${dbtableprefix:-}" ]] && dbtableprefix="oc_"
```

My nextcloud configuration for `dbtableprefix` is `'dbtableprefix' => ''` and it mean that the tables are not prefixed. The calcardbackup does not backup my calendars and addressbooks.
```
+  Looking for calendars in your Nextcloud:
-- NOTICE: table 'oc_calendars' containing calendars does not exist in database.
-- NOTICE: Looks like your Nextcloud did not create any calendars yet.
-- INFO: Couldn't find a single calendar in your Nextcloud!
+  Looking for addressbooks in your Nextcloud:
-- NOTICE: table 'oc_addressbooks' containing addressbooks does not exist in database.
-- NOTICE: Looks like your Nextcloud did not create any addressbooks yet.
-- INFO: Couldn't find a single addressbook in your Nextcloud!
```

**Comment by BernieO** [comment]
Thanks for finding this.
Don‘t know what I thought when I wrote that. Probably not that much...
I will take care of that soonish.

**Comment by BernieO** [comment]
Commit 8f22e669d81a5fb231d6899a8b3b94c042d45a65 fixes this issue.
Currently only in the testing branch (until merged to master for the next release).
