### ISSUE TITLE
Backup bookmarks from bookmark app

### ISSUE THREAD

**Issue by myownhost** [BernieO/calcardbackup#23]
Hi BernieO,
i have a feature request for you very nice backup tool.
Is it possible to integrate a backup of the Bookmarks app?
https://apps.nextcloud.com/apps/bookmarks
Because the bookmarks are also saved in database tables.

Thanks and regards
Rene

**Comment by BernieO** [comment]
I am sorry, *calcardbackup* is only designed as tool to backup calendar and contacts data.

And I quite want to keep it like this, instead of increasing the scripts' complexity by adding features which have nothing to do with the original purpose of the script.
