### ISSUE TITLE
Make vendor detection (also) working by using http

### ISSUE THREAD

**Issue by waja** [BernieO/calcardbackup#5]
With https://github.com/BernieO/calcardbackup/commit/fe7d9d8b97d652dad35c0fbd0f1e103247403b58 you added a (better) detection of the vendor and version. Unfortunately this requires filesystem access to the Nextcloud/Owncloud documentation.

I'm running calcardbackup in a [docker container](https://hub.docker.com/r/waja/calcardbackup/) where the filesystem of Nextcloud/Owncloud is not accessable. Anyway the resource is available also via http://host/base-uri/core/doc/user/index.html and it would be very great to fetch that resource by http (or make it optional) to work around this issue.

Many thanks, Jan.

**Comment by BernieO** [comment]
changed in release 0.4.1 https://github.com/BernieO/calcardbackup/commit/cf71c195431051bb367cb13300c59455dd765bbd

Thanks for the link! I not experienced with docker containers, but I am curious: calcardbackup needs to read config.php. How does that work in your setup without filesystem access?

**Comment by waja** [comment]
>  but I am curious: calcardbackup needs to read config.php. How does that work in your setup without filesystem access?

The config.php is "put" into the container by [bind mount](https://docs.docker.com/storage/bind-mounts/) or [volume](https://docs.docker.com/storage/volumes/) and can be shared between more then one containers in this case.

**Comment by waja** [comment]
Anyway ... 0.4.1 works like charm!
```
nextcloud-nc-backup_1  | +  Checking dependencies and preparing...
nextcloud-nc-backup_1  | +  Using URL https://cloud.test.org
nextcloud-nc-backup_1  | +  Nextcloud 13.0.0 detected.
nextcloud-nc-backup_1  | +  Database of chosen Nextcloud installation is MySQL/MariaDB.
nextcloud-nc-backup_1  | +  Looking for calendars in your Nextcloud:
```
Many thanks!

**Comment by BernieO** [comment]
Great.
Thanks for the explanation. Sounds clever!
