### ISSUE TITLE
not compatible with snap installation

### ISSUE THREAD

**Issue by orcu** [BernieO/calcardbackup#6]
Not directly compatible with snap installation as snap installation comes with a mysql bundle and does not require a standalone mysql server to be installed. 

Notes: 
URL to find configs is:
/var/snap/nextcloud/current/nextcloud/
MySql files are at:
/var/snap/nextcloud/current/mysql/nextcloud

Relevant outputs:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  Mon Apr  9 08:01:12 UTC 2018 --> START calcardbackup ver. 0.4.1 (06.03.2018), AGPL-3.0
+  Checking dependencies and preparing...
+  Using URL <deleted>
+  Nextcloud 12.0.5 detected.
+  Database of chosen Nextcloud installation is MySQL/MariaDB.
+  Looking for calendars in your Nextcloud:
./calcardbackup: line 535: mysql: command not found
-- NOTICE: table 'oc_calendars' containing calendars does not exist in database.
-- NOTICE: Looks like Nextcloud did not create any calendars yet.
-- INFO: Couldn't find a single calendar in your Nextcloud!
+  Not backing up addressbooks as configured.
-- WARNING: No files in backup directory - meaning no backup created !!
+  Mon Apr  9 08:01:13 UTC 2018 --> END calcardbackup
+
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Output after a standalone mysql server is installed:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  Mon Apr  9 08:31:20 UTC 2018 --> START calcardbackup ver. 0.4.1 (06.03.2018), AGPL-3.0
+  Checking dependencies and preparing...
+  Using URL <deleted>
+  Nextcloud 12.0.5 detected.
+  Database of chosen Nextcloud installation is MySQL/MariaDB.
+  Looking for calendars in your Nextcloud:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/sockets/mysql.sock' (2)
-- NOTICE: table 'oc_calendars' containing calendars does not exist in database.
-- NOTICE: Looks like Nextcloud did not create any calendars yet.
-- INFO: Couldn't find a single calendar in your Nextcloud!
+  Not backing up addressbooks as configured.
-- WARNING: No files in backup directory - meaning no backup created !!
+  Mon Apr  9 08:31:21 UTC 2018 --> END calcardbackup
+
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by BernieO** [comment]
Thanks for reporting this. Could you check whether the new option `-p|--snap` in the latest commit in the testing branch (https://github.com/BernieO/calcardbackup/commit/2af9fbebd1912d0ceee676102a1bf9e013dd1497) creates compatibility with Nextcloud-snap?

You have to run calcardbackup with sudo (running as root won‘t work: https://github.com/nextcloud/nextcloud-snap/issues/356#issuecomment-335540294):
`sudo ./calcardbackup /var/snap/nextcloud/current/nextcloud -p`

**Comment by BernieO** [comment]
new option `-p|--snap` in release [0.4.2](https://github.com/BernieO/calcardbackup/tree/v0.4.2) adds support for nextcloud-snap.
